<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
 * Modelo para persistencia  de enfermeria.
 */
class E36_model extends MY_Model
{
    
    protected $table = 'e36';
    
    public $fields = [
        ['field' => 'residente_cedula', 'rules' => 'trim|required|max_length[20]|numeric', 'label' => 'Cedula'],
        ['field' => 'conquien',         'label' => 'Con quién duerme',          'rules' => 'trim|max_length[100]'],
        ['field' => 'deque',            'label' => 'De que vive',               'rules' => 'trim|max_length[150]'],
        ['field' => 'lee',              'label' => 'Lee',                       'rules' => 'trim|max_length[5]'],
        ['field' => 'escribe',          'label' => 'Escribe',                   'rules' => 'trim|max_length[5]'],
        ['field' => 'otrainstitucion',  'label' => 'Intituciones pasadas',      'rules' => 'trim|max_length[50]'],
        ['field' => 'enfermedades',     'label' => 'Enfermedades',              'rules' => 'trim|max_length[300]'],
        ['field' => 'motivoingresar',   'label' => 'Motivo ingreso',            'rules' => 'trim|max_length[200]'],
        ['field' => 'tratamientopsi',   'label' => 'Tratamientos psicológicos', 'rules' => 'trim|max_length[150]'],
        ['field' => 'drogapsi',         'label' => 'Drogas psicológicas',       'rules' => 'trim|max_length[150]'],
        ['field' => 'problemasfamilia', 'label' => 'Problemas mentales familiares','rules' => 'trim|max_length[200]'],
        ['field' => 'satisfecho',       'label' => 'Satisfecho',                'rules' => 'trim|max_length[5]'],
        ['field' => 'disminuidointeres','label' => 'Interés disminuido',        'rules' => 'trim|max_length[5]'],
        ['field' => 'vidavacia',        'label' => 'Vida vacía',                'rules' => 'trim|max_length[5]'],
        ['field' => 'aburrido',         'label' => 'Aburrido',                  'rules' => 'trim|max_length[5]'],
        ['field' => 'buenanimo',        'label' => 'Buen ánimo',                'rules' => 'trim|max_length[5]'],
        ['field' => 'temor',            'label' => 'Temor',                     'rules' => 'trim|max_length[5]'],
        ['field' => 'feliz',            'label' => 'Felicidad',                 'rules' => 'trim|max_length[5]'],
        ['field' => 'desamparado',      'label' => 'Desamparado',               'rules' => 'trim|max_length[5]'],
        ['field' => 'encasaosalir',     'label' => 'Permanencia en casa',       'rules' => 'trim|max_length[5]'],
        ['field' => 'memoria',          'label' => 'Problemas de memoria',      'rules' => 'trim|max_length[5]'],
        ['field' => 'estarvivo',        'label' => 'Fascinación por la vida',   'rules' => 'trim|max_length[5]'],
        ['field' => 'inutil',           'label' => 'Sentimiento de inutileza',  'rules' => 'trim|max_length[5]'],
        ['field' => 'energia',          'label' => 'Lleno de Energia',          'rules' => 'trim|max_length[5]'],
        ['field' => 'sinesperanza',     'label' => 'Sin esperanza',             'rules' => 'trim|max_length[5]'],
        ['field' => 'otrosmejor',       'label' => 'Otrosmejor',                'rules' => 'trim|max_length[5]'],
        ['field' => 'quepreocupa',      'label' => 'Preocupaciones',            'rules' => 'trim|max_length[150]'],
        ['field' => 'quetriste',        'label' => 'Tristezas',                 'rules' => 'trim|max_length[150]'],
        ['field' => 'quemolesta',       'label' => 'Molestias',                 'rules' => 'trim|max_length[150]'],
        ['field' => 'duerme',           'label' => 'Duerme',                    'rules' => 'trim|max_length[5]'],
        ['field' => 'horasduerme',      'label' => 'Horas de sueño',            'rules' => 'trim|numeric'],
        ['field' => 'noharia',          'label' => 'No volvería a hacer',       'rules' => 'trim|max_length[200]'],
        ['field' => 'depresion',        'label' => 'Depresion',                 'rules' => 'trim|max_length[10]'],
        ['field' => 'familia',          'label' => 'Área familiar',             'rules' => 'trim|max_length[400]'],
        ['field' => 'socialanterior',   'label' => 'Area social anteior',       'rules' => 'trim|max_length[400]'],
        ['field' => 'socialactual',     'label' => 'Area social actual',        'rules' => 'trim|max_length[400]'],
        ['field' => 'lollamavisita',    'label' => 'Llamadas y visitas de amigos', 'rules' => 'trim|max_length[20]'],
        ['field' => 'llamavisita',      'label' => 'Llamar y visitar amigos',   'rules' => 'trim|max_length[20]'],
        ['field' => 'divierte',         'label' => 'Área recreativa',           'rules' => 'trim|max_length[200]'],
        ['field' => 'gustadivertirse',  'label' => 'Área recreativa',           'rules' => 'trim|max_length[200]'],
        ['field' => 'quienesvisita',    'label' => 'Visitas',                   'rules' => 'trim|max_length[300]'],
        ['field' => 'quienestelefono',  'label' => 'Contácto telefónico',       'rules' => 'trim|max_length[300]'],
        ['field' => 'tienetrabajo',     'label' => 'Tienetrabajo',              'rules' => 'trim|max_length[5]'],
        ['field' => 'desdeedad',        'label' => 'Edad de inicio de trabajo', 'rules' => 'trim|numeric'],
        ['field' => 'labores',          'label' => 'Labores realizadas',        'rules' => 'trim|max_length[150]'],
        ['field' => 'hacecuantodejo',   'label' => 'Tiempo desde finalización de trabajo', 'rules' => 'trim|max_length[50]'],
        ['field' => 'areareligiosa',    'label' => 'Área religiosa',            'rules' => 'trim|max_length[200]'],
        ['field' => 'actividadesdificil','label' => 'Actividades con dificultad','rules' => 'trim|max_length[200]'],
        ['field' => 'actividadesgustaria','label' => 'Actividades que desearía','rules' => 'trim|max_length[200]'],
        ['field' => 'fundacionbrinda',  'label' => 'La fundación debe brindar', 'rules' => 'trim|max_length[200]'],
        ['field' => 'gustariahacer',    'label' => 'Gustaría hacer en su vida', 'rules' => 'trim|max_length[200]'],
        ['field' => 'deseahacervida',   'label' => 'Desearía hacer en su vida', 'rules' => 'trim|max_length[200]'],
        ['field' => 'en6meses',         'label' => 'En 6 meses',                'rules' => 'trim|max_length[400]'],
        ['field' => 'en1anio',          'label' => 'En 1 año',                  'rules' => 'trim|max_length[400]'],
        ['field' => 'satisfechovida',   'label' => 'Satisfacción con la vida',  'rules' => 'trim|max_length[300]'],
        ['field' => 'comprar',          'label' => 'Compras',                   'rules' => 'trim|max_length[300]'],
        ['field' => 'puntajeorientacion','label' => 'Puntaje: orientación',     'rules' => 'trim|numeric'],
        ['field' => 'puntajememoria',   'label' => 'Puntaje: memoria',          'rules' => 'trim|numeric'],
        ['field' => 'puntajecalculo',   'label' => 'Puntaje: calculo',          'rules' => 'trim|numeric'],
        ['field' => 'puntajeevocacion', 'label' => 'Puntaje: evocación',        'rules' => 'trim|numeric'],
        ['field' => 'puntaje2objetos',  'label' => 'Puntaje: nombrar 2 objetos','rules' => 'trim|numeric'],
        ['field' => 'puntajerepetir',   'label' => 'Puntaje: repetir',          'rules' => 'trim|numeric'],
        ['field' => 'puntajeobedecer',  'label' => 'Puntaje: obedecer',         'rules' => 'trim|numeric'],
        ['field' => 'puntajeleeobedece','label' => 'Puntaje: leer y obedecer',  'rules' => 'trim|numeric'],
        ['field' => 'puntajeescribefrase','label' => 'Puntaje: escribir frase', 'rules' => 'trim|numeric'],
        ['field' => 'puntajemilitarcrus','label' => 'Puntaje: saludo militar y cruz','rules' => 'trim|numeric'],
        ['field' => 'puntajecopia',     'label' => 'Puntaje: copiar diseño',    'rules' => 'trim|numeric'],
        ['field' => 'similarfrutas',    'label' => 'Similitud 1',               'rules' => 'trim|max_length[100]'],
        ['field' => 'similarropa',      'label' => 'Similutd 2',                'rules' => 'trim|max_length[100]'],
        ['field' => 'similaranimal',    'label' => 'Similitud 3',               'rules' => 'trim|max_length[100]'],
        ['field' => 'refrancaballo',    'label' => 'Refrán 1',                  'rules' => 'trim|max_length[150]'],
        ['field' => 'refranrio',        'label' => 'Refrán 2',                  'rules' => 'trim|max_length[150]'],
        ['field' => 'solucioninunda',   'label' => 'Inundación',                'rules' => 'trim|max_length[400]'],
        ['field' => 'memoriadesayuno',  'label' => 'Qué desayunó',              'rules' => 'trim|max_length[200]'],
        ['field' => 'memoriaalmuerzo',  'label' => 'Qué almorzó',               'rules' => 'trim|max_length[200]'],
        ['field' => 'memoriaayer',      'label' => 'Qué hizo ayer',             'rules' => 'trim|max_length[200]'],
        ['field' => 'praxiafosforos',   'label' => 'Praxia 1',                  'rules' => 'trim|max_length[100]'],
        ['field' => 'praxiamartillo',   'label' => 'Praxia 2',                  'rules' => 'trim|max_length[100]'],
        ['field' => 'olvidointencion',  'label' => 'Olvido de intención',       'rules' => 'trim|max_length[5]'],
        ['field' => 'defectoatencion',  'label' => 'Defecto de atención',       'rules' => 'trim|max_length[5]'],
        ['field' => 'esfinteres',       'label' => 'Esfínteres',                'rules' => 'trim|max_length[5]'],
        ['field' => 'desconfianza',     'label' => 'Desconfianza',              'rules' => 'trim|max_length[5]'],
        ['field' => 'agresividadverbal','label' => 'Agresividad verbal',        'rules' => 'trim|max_length[5]'],
        ['field' => 'tendenciasmalas',  'label' => 'Tendencias y addiciones',   'rules' => 'trim|max_length[5]'],
        ['field' => 'fatiga',           'label' => 'Fatiga',                    'rules' => 'trim|max_length[5]'],
        ['field' => 'descuidopersonal', 'label' => 'Descuido personal',         'rules' => 'trim|max_length[5]'],
        ['field' => 'rupturanormas',    'label' => 'Ruptura de normas sociales','rules' => 'trim|max_length[5]'],
        ['field' => 'labialidad',       'label' => 'Labialidad',                'rules' => 'trim|max_length[5]'],
        ['field' => 'celos',            'label' => 'Celos',                     'rules' => 'trim|max_length[5]'],
        ['field' => 'apatia',           'label' => 'Apatia',                    'rules' => 'trim|max_length[5]'],
        ['field' => 'irrita',           'label' => 'Irritabilidad',             'rules' => 'trim|max_length[5]'],
        ['field' => 'impresion',        'label' => 'Impresión',                 'rules' => 'trim|max_length[600]'],
        ['field' => 'fechahora',        'label' => 'Fecha de terminación',      'rules' => 'trim'],
    ];

    
}
?>
